import { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="descriprion" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome to <a href="https://next.js.org">Next.js!</a></h1>

        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, ex vel? Harum soluta consequuntur dolores sunt, commodi quae aperiam officiis, dignissimos tempora debitis id aspernatur, sed qui facilis earum unde.</p>

      </main>
    </>
  )
}

export default Home
  
